### https://github.com/golangci/golangci-lint
###------------------------------------------

linters:
  enable-all: true
  disable:
    - gochecknoglobals
    - gochecknoinits
    - godot
    - gomnd
